#!/usr/bin/env bash

echo "SETTING UP RPI:" &&\

ssh "dsp@peg" "
set -x
mkdir -p /home/dsp/firmware
mkdir -p /home/dsp/ui
sudo rm /home/dsp/firmware/*
sudo rm /home/dsp/ui/*
" && \


echo "COPYING USERSPACE BINARY TO RPI:" &&\
scp result/bin/DSP-PEG-ui peg:/home/dsp/ui/

echo "COPYING FIRMWARE TO RPI:" &&\
scp result/baremetal/dsp_peg_fw.bin peg:/home/dsp/firmware/ &&\


echo "FINISHING SETUP..."

ssh "dsp@peg" "
set -x
chmod 700 /home/dsp/DSP-PEG-ui
sudo rm /lib/firmware/dsp_peg_fw.bin
sudo mv /home/dsp/firmware/dsp_peg_fw.bin /lib/firmware
"

